# Generated by Django 3.2.9 on 2021-12-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(default='lastname', max_length=100)),
                ('first_name', models.CharField(default='first', max_length=100)),
                ('phone_number', models.CharField(default='phone', max_length=100)),
                ('email', models.CharField(default='email', max_length=100)),
            ],
        ),
    ]
