# Generated by Django 3.2.9 on 2021-12-06 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_num', models.IntegerField()),
                ('account_name', models.CharField(default='My Account', max_length=100)),
                ('account_type', models.CharField(default='Checking', max_length=100)),
                ('account_bal', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='bank', max_length=100)),
                ('routing_number', models.IntegerField()),
                ('bank_phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CardInfo',
            fields=[
                ('card_number', models.IntegerField()),
                ('card_holder', models.CharField(default='holder', max_length=100)),
                ('card_issuer', models.CharField(default='issuer', max_length=100)),
                ('security_code', models.CharField(default='000', max_length=3)),
                ('expiration', models.CharField(default='MM/YY', max_length=100)),
                ('last_four_digits', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(default='lastname', max_length=100)),
                ('first_name', models.CharField(default='first', max_length=100)),
                ('phone_number', models.CharField(default='phone', max_length=100)),
                ('email', models.CharField(default='email', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('previous_balance', models.FloatField()),
                ('amount_paid', models.FloatField()),
                ('new_balance', models.FloatField()),
                ('account_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.account')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('last_four_digits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cardinfo')),
            ],
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.AddField(
            model_name='account',
            name='bank_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.bank'),
        ),
        migrations.AddField(
            model_name='account',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
    ]
