# Generated by Django 3.2.9 on 2021-12-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='routing_number',
            field=models.BigIntegerField(),
        ),
    ]
