# Generated by Django 3.2.9 on 2021-12-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='bank', max_length=100)),
                ('routing_number', models.IntegerField()),
                ('bank_phone', models.CharField(max_length=100)),
            ],
        ),
    ]
