# Generated by Django 3.2.9 on 2021-12-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_bank_routing_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_num',
            field=models.BigIntegerField(),
        ),
    ]
