# Generated by Django 3.2.9 on 2021-12-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_account_account_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardinfo',
            name='card_number',
            field=models.BigIntegerField(),
        ),
    ]
