# Generated by Django 3.2.9 on 2021-12-05 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211205_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardInfo',
            fields=[
                ('card_number', models.IntegerField()),
                ('card_holder', models.CharField(default='holder', max_length=100)),
                ('card_issuer', models.CharField(default='issuer', max_length=100)),
                ('security_code', models.IntegerField()),
                ('expiration', models.CharField(default='MM/YY', max_length=100)),
                ('last_four_digits', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
            ],
        ),
    ]
