# Generated by Django 3.2.9 on 2021-12-05 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_cardinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accounts',
            new_name='Account',
        ),
    ]
