# Generated by Django 3.2.9 on 2021-12-05 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_accounts_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('previous_balance', models.DecimalField(decimal_places=2, max_digits=100)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=100)),
                ('new_balance', models.DecimalField(decimal_places=2, max_digits=100)),
                ('account_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.account')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('last_four_digits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cardinfo')),
            ],
        ),
    ]
