# Generated by Django 3.2.9 on 2021-12-05 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_transactions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
    ]
