# Generated by Django 3.2.9 on 2021-12-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_transactions_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_bal',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='security_code',
            field=models.CharField(default='000', max_length=3),
        ),
    ]
